/**
 * This file is part of Kowy Maker.
 *
 * Kowy Maker is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Kowy Maker is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Kowy Maker.  If not, see <http://www.gnu.org/licenses/gpl-3.0.txt>.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package com.kowymaker.spec.proto;

public final class NetworkCodecs
{
    private NetworkCodecs()
    {
    }
    
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry)
    {
    }
    
    public interface ConnectMessageOrBuilder extends
            com.google.protobuf.MessageOrBuilder
    {
        
        // required string name = 1;
        boolean hasName();
        
        String getName();
    }
    
    public static final class ConnectMessage extends
            com.google.protobuf.GeneratedMessage implements
            ConnectMessageOrBuilder
    {
        // Use ConnectMessage.newBuilder() to construct.
        private ConnectMessage(Builder builder)
        {
            super(builder);
        }
        
        private ConnectMessage(boolean noInit)
        {
        }
        
        private static final ConnectMessage defaultInstance;
        
        public static ConnectMessage getDefaultInstance()
        {
            return defaultInstance;
        }
        
        public ConnectMessage getDefaultInstanceForType()
        {
            return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor()
        {
            return com.kowymaker.spec.proto.NetworkCodecs.internal_static_com_kowymaker_spec_proto_ConnectMessage_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable()
        {
            return com.kowymaker.spec.proto.NetworkCodecs.internal_static_com_kowymaker_spec_proto_ConnectMessage_fieldAccessorTable;
        }
        
        private int              bitField0_;
        // required string name = 1;
        public static final int  NAME_FIELD_NUMBER = 1;
        private java.lang.Object name_;
        
        public boolean hasName()
        {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        
        public String getName()
        {
            java.lang.Object ref = name_;
            if (ref instanceof String)
            {
                return (String) ref;
            }
            else
            {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs))
                {
                    name_ = s;
                }
                return s;
            }
        }
        
        private com.google.protobuf.ByteString getNameBytes()
        {
            java.lang.Object ref = name_;
            if (ref instanceof String)
            {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((String) ref);
                name_ = b;
                return b;
            }
            else
            {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        private void initFields()
        {
            name_ = "";
        }
        
        private byte memoizedIsInitialized = -1;
        
        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;
            
            if (!hasName())
            {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException
        {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001))
            {
                output.writeBytes(1, getNameBytes());
            }
            getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        
        public int getSerializedSize()
        {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;
            
            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001))
            {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(
                        1, getNameBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }
        
        private static final long serialVersionUID = 0L;
        
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException
        {
            return super.writeReplace();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseFrom(
                byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseFrom(
                java.io.InputStream input) throws java.io.IOException
        {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException
        {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input))
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry))
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException
        {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }
        
        public static Builder newBuilder()
        {
            return Builder.create();
        }
        
        public Builder newBuilderForType()
        {
            return newBuilder();
        }
        
        public static Builder newBuilder(
                com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage prototype)
        {
            return newBuilder().mergeFrom(prototype);
        }
        
        public Builder toBuilder()
        {
            return newBuilder(this);
        }
        
        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent)
        {
            Builder builder = new Builder(parent);
            return builder;
        }
        
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                com.kowymaker.spec.proto.NetworkCodecs.ConnectMessageOrBuilder
        {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor()
            {
                return com.kowymaker.spec.proto.NetworkCodecs.internal_static_com_kowymaker_spec_proto_ConnectMessage_descriptor;
            }
            
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable()
            {
                return com.kowymaker.spec.proto.NetworkCodecs.internal_static_com_kowymaker_spec_proto_ConnectMessage_fieldAccessorTable;
            }
            
            // Construct using
            // com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }
            
            private Builder(BuilderParent parent)
            {
                super(parent);
                maybeForceBuilderInitialization();
            }
            
            private void maybeForceBuilderInitialization()
            {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders)
                {
                }
            }
            
            private static Builder create()
            {
                return new Builder();
            }
            
            public Builder clear()
            {
                super.clear();
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }
            
            public Builder clone()
            {
                return create().mergeFrom(buildPartial());
            }
            
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType()
            {
                return com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage
                        .getDescriptor();
            }
            
            public com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage getDefaultInstanceForType()
            {
                return com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage
                        .getDefaultInstance();
            }
            
            public com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage build()
            {
                com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }
            
            private com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException(result)
                            .asInvalidProtocolBufferException();
                }
                return result;
            }
            
            public com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage buildPartial()
            {
                com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage result = new com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001))
                {
                    to_bitField0_ |= 0x00000001;
                }
                result.name_ = name_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }
            
            public Builder mergeFrom(com.google.protobuf.Message other)
            {
                if (other instanceof com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage)
                {
                    return mergeFrom((com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage) other);
                }
                else
                {
                    super.mergeFrom(other);
                    return this;
                }
            }
            
            public Builder mergeFrom(
                    com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage other)
            {
                if (other == com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage
                        .getDefaultInstance())
                    return this;
                if (other.hasName())
                {
                    setName(other.getName());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }
            
            public final boolean isInitialized()
            {
                if (!hasName())
                {
                    
                    return false;
                }
                return true;
            }
            
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                        .newBuilder(this.getUnknownFields());
                while (true)
                {
                    int tag = input.readTag();
                    switch (tag)
                    {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default:
                        {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag))
                            {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10:
                        {
                            bitField0_ |= 0x00000001;
                            name_ = input.readBytes();
                            break;
                        }
                    }
                }
            }
            
            private int              bitField0_;
            
            // required string name = 1;
            private java.lang.Object name_ = "";
            
            public boolean hasName()
            {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            
            public String getName()
            {
                java.lang.Object ref = name_;
                if (!(ref instanceof String))
                {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    name_ = s;
                    return s;
                }
                else
                {
                    return (String) ref;
                }
            }
            
            public Builder setName(String value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }
            
            public Builder clearName()
            {
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            
            void setName(com.google.protobuf.ByteString value)
            {
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
            }
            
            // @@protoc_insertion_point(builder_scope:com.kowymaker.spec.proto.ConnectMessage)
        }
        
        static
        {
            defaultInstance = new ConnectMessage(true);
            defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:com.kowymaker.spec.proto.ConnectMessage)
    }
    
    public interface DisconnectMessageOrBuilder extends
            com.google.protobuf.MessageOrBuilder
    {
        
        // required string name = 1;
        boolean hasName();
        
        String getName();
    }
    
    public static final class DisconnectMessage extends
            com.google.protobuf.GeneratedMessage implements
            DisconnectMessageOrBuilder
    {
        // Use DisconnectMessage.newBuilder() to construct.
        private DisconnectMessage(Builder builder)
        {
            super(builder);
        }
        
        private DisconnectMessage(boolean noInit)
        {
        }
        
        private static final DisconnectMessage defaultInstance;
        
        public static DisconnectMessage getDefaultInstance()
        {
            return defaultInstance;
        }
        
        public DisconnectMessage getDefaultInstanceForType()
        {
            return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor()
        {
            return com.kowymaker.spec.proto.NetworkCodecs.internal_static_com_kowymaker_spec_proto_DisconnectMessage_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable()
        {
            return com.kowymaker.spec.proto.NetworkCodecs.internal_static_com_kowymaker_spec_proto_DisconnectMessage_fieldAccessorTable;
        }
        
        private int              bitField0_;
        // required string name = 1;
        public static final int  NAME_FIELD_NUMBER = 1;
        private java.lang.Object name_;
        
        public boolean hasName()
        {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        
        public String getName()
        {
            java.lang.Object ref = name_;
            if (ref instanceof String)
            {
                return (String) ref;
            }
            else
            {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs))
                {
                    name_ = s;
                }
                return s;
            }
        }
        
        private com.google.protobuf.ByteString getNameBytes()
        {
            java.lang.Object ref = name_;
            if (ref instanceof String)
            {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((String) ref);
                name_ = b;
                return b;
            }
            else
            {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        private void initFields()
        {
            name_ = "";
        }
        
        private byte memoizedIsInitialized = -1;
        
        public final boolean isInitialized()
        {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;
            
            if (!hasName())
            {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException
        {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001))
            {
                output.writeBytes(1, getNameBytes());
            }
            getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        
        public int getSerializedSize()
        {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;
            
            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001))
            {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(
                        1, getNameBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }
        
        private static final long serialVersionUID = 0L;
        
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException
        {
            return super.writeReplace();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseFrom(
                byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException
        {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseFrom(
                java.io.InputStream input) throws java.io.IOException
        {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException
        {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input))
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry))
            {
                return builder.buildParsed();
            }
            else
            {
                return null;
            }
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException
        {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        
        public static com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException
        {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }
        
        public static Builder newBuilder()
        {
            return Builder.create();
        }
        
        public Builder newBuilderForType()
        {
            return newBuilder();
        }
        
        public static Builder newBuilder(
                com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage prototype)
        {
            return newBuilder().mergeFrom(prototype);
        }
        
        public Builder toBuilder()
        {
            return newBuilder(this);
        }
        
        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent)
        {
            Builder builder = new Builder(parent);
            return builder;
        }
        
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements
                com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessageOrBuilder
        {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor()
            {
                return com.kowymaker.spec.proto.NetworkCodecs.internal_static_com_kowymaker_spec_proto_DisconnectMessage_descriptor;
            }
            
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable()
            {
                return com.kowymaker.spec.proto.NetworkCodecs.internal_static_com_kowymaker_spec_proto_DisconnectMessage_fieldAccessorTable;
            }
            
            // Construct using
            // com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage.newBuilder()
            private Builder()
            {
                maybeForceBuilderInitialization();
            }
            
            private Builder(BuilderParent parent)
            {
                super(parent);
                maybeForceBuilderInitialization();
            }
            
            private void maybeForceBuilderInitialization()
            {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders)
                {
                }
            }
            
            private static Builder create()
            {
                return new Builder();
            }
            
            public Builder clear()
            {
                super.clear();
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }
            
            public Builder clone()
            {
                return create().mergeFrom(buildPartial());
            }
            
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType()
            {
                return com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage
                        .getDescriptor();
            }
            
            public com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage getDefaultInstanceForType()
            {
                return com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage
                        .getDefaultInstance();
            }
            
            public com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage build()
            {
                com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }
            
            private com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException
            {
                com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage result = buildPartial();
                if (!result.isInitialized())
                {
                    throw newUninitializedMessageException(result)
                            .asInvalidProtocolBufferException();
                }
                return result;
            }
            
            public com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage buildPartial()
            {
                com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage result = new com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001))
                {
                    to_bitField0_ |= 0x00000001;
                }
                result.name_ = name_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }
            
            public Builder mergeFrom(com.google.protobuf.Message other)
            {
                if (other instanceof com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage)
                {
                    return mergeFrom((com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage) other);
                }
                else
                {
                    super.mergeFrom(other);
                    return this;
                }
            }
            
            public Builder mergeFrom(
                    com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage other)
            {
                if (other == com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage
                        .getDefaultInstance())
                    return this;
                if (other.hasName())
                {
                    setName(other.getName());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }
            
            public final boolean isInitialized()
            {
                if (!hasName())
                {
                    
                    return false;
                }
                return true;
            }
            
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException
            {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                        .newBuilder(this.getUnknownFields());
                while (true)
                {
                    int tag = input.readTag();
                    switch (tag)
                    {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default:
                        {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag))
                            {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10:
                        {
                            bitField0_ |= 0x00000001;
                            name_ = input.readBytes();
                            break;
                        }
                    }
                }
            }
            
            private int              bitField0_;
            
            // required string name = 1;
            private java.lang.Object name_ = "";
            
            public boolean hasName()
            {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            
            public String getName()
            {
                java.lang.Object ref = name_;
                if (!(ref instanceof String))
                {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    name_ = s;
                    return s;
                }
                else
                {
                    return (String) ref;
                }
            }
            
            public Builder setName(String value)
            {
                if (value == null)
                {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }
            
            public Builder clearName()
            {
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            
            void setName(com.google.protobuf.ByteString value)
            {
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
            }
            
            // @@protoc_insertion_point(builder_scope:com.kowymaker.spec.proto.DisconnectMessage)
        }
        
        static
        {
            defaultInstance = new DisconnectMessage(true);
            defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:com.kowymaker.spec.proto.DisconnectMessage)
    }
    
    private static com.google.protobuf.Descriptors.Descriptor              internal_static_com_kowymaker_spec_proto_ConnectMessage_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_kowymaker_spec_proto_ConnectMessage_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor              internal_static_com_kowymaker_spec_proto_DisconnectMessage_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_kowymaker_spec_proto_DisconnectMessage_fieldAccessorTable;
    
    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor()
    {
        return descriptor;
    }
    
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static
    {
        java.lang.String[] descriptorData = { "\n\tnet.proto\022\030com.kowymaker.spec.proto\"\036\n"
                + "\016ConnectMessage\022\014\n\004name\030\001 \002(\t\"!\n\021Disconn"
                + "ectMessage\022\014\n\004name\030\001 \002(\tB\017B\rNetworkCodec"
                + "s" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root)
            {
                descriptor = root;
                internal_static_com_kowymaker_spec_proto_ConnectMessage_descriptor = getDescriptor()
                        .getMessageTypes().get(0);
                internal_static_com_kowymaker_spec_proto_ConnectMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_com_kowymaker_spec_proto_ConnectMessage_descriptor,
                        new java.lang.String[] { "Name", },
                        com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage.class,
                        com.kowymaker.spec.proto.NetworkCodecs.ConnectMessage.Builder.class);
                internal_static_com_kowymaker_spec_proto_DisconnectMessage_descriptor = getDescriptor()
                        .getMessageTypes().get(1);
                internal_static_com_kowymaker_spec_proto_DisconnectMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_com_kowymaker_spec_proto_DisconnectMessage_descriptor,
                        new java.lang.String[] { "Name", },
                        com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage.class,
                        com.kowymaker.spec.proto.NetworkCodecs.DisconnectMessage.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(
                        descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {},
                        assigner);
    }
    
    // @@protoc_insertion_point(outer_class_scope)
}
